# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devtap < Formula
  desc "Bridge build/dev process output to AI coding sessions"
  homepage "https://github.com/killme2008/devtap"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.8/devtap_darwin_amd64.tar.gz"
      sha256 "44f01a12a191943251819d6859aca9f36888ec77854680fbe62748a313f07a51"

      def install
        bin.install "devtap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.8/devtap_darwin_arm64.tar.gz"
      sha256 "9aa3fe2a24142ba8b45ba68f75efa4b067152460d22ffcca36065a7ca7e9676d"

      def install
        bin.install "devtap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.8/devtap_linux_amd64.tar.gz"
      sha256 "06de5fbb3f473f2d934d9d1e1f66c9c3030b79b2412350fe627056549537fc53"
      def install
        bin.install "devtap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.8/devtap_linux_arm64.tar.gz"
      sha256 "fe8286fbbf92dd2f4e1547de50f5aa716fd63192b9c3c705204ea9e17f6e5860"
      def install
        bin.install "devtap"
      end
    end
  end

  test do
    system "#{bin}/devtap", "--version"
  end
end
