# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devtap < Formula
  desc "Bridge build/dev process output to AI coding sessions"
  homepage "https://github.com/killme2008/devtap"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.5/devtap_darwin_amd64.tar.gz"
      sha256 "36ab0901080431d83cf947b94eacc65e48d1b33fdc8d95a94991994917cac905"

      def install
        bin.install "devtap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.5/devtap_darwin_arm64.tar.gz"
      sha256 "57d3009a4a257a334fe0388d917a0157070a552205e65fdf6e80d76ca750563c"

      def install
        bin.install "devtap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.5/devtap_linux_amd64.tar.gz"
      sha256 "3709a8622080d6a1a27d6e6a5ed2757101858952c6e68493f9b28bef4503e81b"
      def install
        bin.install "devtap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/killme2008/devtap/releases/download/v0.1.5/devtap_linux_arm64.tar.gz"
      sha256 "90384b9ab7d4797894a34c107f43b5aee4acf05f492bf45013d1c3d66f61931c"
      def install
        bin.install "devtap"
      end
    end
  end

  test do
    system "#{bin}/devtap", "--version"
  end
end
